project:
  type: website

website:
  title: "Tyler McCormick DSAN-5000: Project thm12"
  sidebar:
    contents:
      - href: index.qmd
        text: Introduction
      - href: about.qmd
        text: About me
      - href: https://github.com/anly501/dsan-5000-project-thm12
        text: Code
      - href: https://github.com/anly501/dsan-5000-project-thm12/tree/main/data
        text: Data
      - href: gathering.ipynb
        text: Data Gathering
      - href: cleaning.ipynb
        text: Data Cleaning
      - href: eda/eda.ipynb
        text: Data Exploration
      - href: bayes.ipynb
        text: Naive Bayes
      - href: clustering/clustering.ipynb
        text: Clustering
      - href: dimensionality.ipynb
        text: Dimensionality Reduction
      - href: decision.qmd
        text: Decision Trees
      - href: arm.qmd
        text: ARM
      - href: conclusion.qmd
        text: Conclusions
      
format:
  html:
    theme: cosmo
    toc: true


bibliography: sources.bib
